### PR TITLE
Update to 1.19.1

### PR DESCRIPTION
**Pull request by Trains77**
Updates the mod to work with version 1.19.1

### CODE REVIEW

**Comment by Trains77** [comment]
Also works with 1.19.2

**Comment by BradyXD** [comment]
Hi there. Could you please help me with building a .jar file out of this? I really have 0 clue what I'm doing and I'd like to use the mod for 1.19.2.

**Comment by Trains77** [comment]
You need to first download the project, which can be done by navigating to my fork and clicking on the green button labeled Code and selecting download zip. Then extract it to somewhere

Open Powershell, or Terminal if you use Linux and navigate to the folder by running "cd C:\Path\to\Folder"

then run "./gradle.bat build" on Windows or "./gradlew build" on Linux

Once it is done navigate to build/libs in the project folder and copy the labeled "ProxyServer-1.3.jar" to your minecraft mods folder it is NOT the sources.jar file

I have only been able to test it on my Linux system but it should work fine on Windows as well

**Comment by BradyXD** [comment]
You absolute legend, it worked! Thank you for the amazing help gamer.

**Pull request merged**
